### ISSUE TITLE
Hi, can u write a readme, ty

### ISSUE THREAD

**Issue by Ritian-Li** [hermanprawiro/tvl1_extractor#1]
I want to know what's that mean
![image](https://user-images.githubusercontent.com/60093100/103517949-e7c9c180-4ead-11eb-8a38-23b5b88de3b9.png)

**Comment by hermanprawiro** [comment]
Hi, it's a script that I use to visualize flow file into image file. It'll call [flow2image](https://github.com/georgegach/flowiz/tree/3812877a2c2c280dff86f96f49a8a9fcd662c683).
